Repository DonkeyKongJr/pimlify, pull requests merged in 2018-07, with the labels that each got.

#10 Add travis and firebase basic configuration
  .travis.yml
  src/pimlify-vue/package-lock.json
  src/pimlify-vue/package.json
  src/pimlify-vue/src/firebase-config.ts
  src/pimlify-vue/src/main.ts
Labels: enhancement

#12 Add build command to readme
  README.md
Labels: documentation

#13 Fix config
  src/pimlify-vue/src/main.ts
Labels: bug

#14 Add Restaurant Component and Firebase retrieval of data
  src/pimlify-vue/package-lock.json
  src/pimlify-vue/package.json
  src/pimlify-vue/src/components/App.vue
  src/pimlify-vue/src/components/OrderMenu.vue
  src/pimlify-vue/src/components/RestaurantComponent.vue
  src/pimlify-vue/src/main.ts
  src/pimlify-vue/src/router.ts
  src/pimlify-vue/src/store/actions.ts
  src/pimlify-vue/src/store/mutation-types.ts
  src/pimlify-vue/src/store/mutations.ts
  src/pimlify-vue/src/store/state.ts
Labels: enhancement

#17 Add configuration and documentation for firebase hosting
  README.md
  src/pimlify-vue/.firebaserc
  src/pimlify-vue/firebase.json
Labels: documentation

#19 Add Register Component and logic
  src/pimlify-vue/src/components/RegisterComponent.vue
  src/pimlify-vue/src/router.ts
  src/pimlify-vue/src/store/actions.ts
  src/pimlify-vue/src/store/mutation-types.ts
  src/pimlify-vue/tsconfig.json
Labels: enhancement

#20 Refactor/menu
  src/pimlify-vue/package-lock.json
  src/pimlify-vue/src/auto-id.ts
  src/pimlify-vue/src/components/App.vue
  src/pimlify-vue/src/components/Home.vue
  src/pimlify-vue/src/components/OrderMenu.vue
  src/pimlify-vue/src/components/Restaurant.vue
  src/pimlify-vue/src/main.ts
  src/pimlify-vue/src/router.ts
  src/pimlify-vue/src/store/actions.ts
  src/pimlify-vue/src/store/getters.ts
  src/pimlify-vue/src/store/index.ts
  src/pimlify-vue/src/store/mutation-types.ts
  src/pimlify-vue/src/store/mutations.ts
  src/pimlify-vue/src/store/state.ts
  src/pimlify-vue/tsconfig.json
Labels: enhancement

#25 Add basic login and Logout mechanism and tslint
  README.md
  src/pimlify-vue/package-lock.json
  src/pimlify-vue/src/components/Login.vue
  src/pimlify-vue/src/components/OrderMenu.vue
  src/pimlify-vue/src/components/Register.vue
  src/pimlify-vue/src/router.ts
  src/pimlify-vue/src/store/actions.ts
  src/pimlify-vue/src/store/mutations.ts
  src/pimlify-vue/src/store/state.ts
  src/pimlify-vue/tslint.json
Labels: enhancement

#31 fix(travis badge): changed to correct md version.
  README.md
Labels: bug

#33 Add deploy to travis
  .travis.yml
  README.md
Labels: enhancement

#44 Add specific project name
  .travis.yml
Labels: enhancement
